defaults:
  - exp_config:
    - data_config:
      - data_root: "data"
      - output_root: "outputs"
      - dataset: "CIFAR10"
    
    - num_samples: 3000
    - batch_size: 128
  
  - solvers: [euler]